version = 0.1
default-task = 'build'
extensions = ['chomp@0.1:npm', './scripts/static-site-generator.js']

[server]
root = "public_html"

[[task]]
name = 'build'
deps = ['copy:css', 'generate:site', 'generate:api-docs']

[[task]]
name = 'copy:css'
targets = ['public_html/codemirror.css', 'public_html/lint.css']
invalidation = 'always'
run = '''
  curl "https://ga.jspm.io/npm:codemirror@5" -o codemirror.version
  curl "https://ga.jspm.io/npm:codemirror@$(cat codemirror.version)/lib/codemirror.css" -o public_html/codemirror.css
  curl "https://ga.jspm.io/npm:codemirror@$(cat codemirror.version)/addon/lint/lint.css" -o public_html/lint.css
  rm codemirror.version
'''

[[task]]
name = 'generate:site'
template = 'static-site-generator'
[task.template-options]
template = 'template.html'
pages = 'pages'
public-html = 'public_html'
feed = 'feed.json'
feed-exclude = ['pages/docs/', 'pages/index.md']
site-name = 'jspm.org'
site-url = 'https://jspm.org/'
site-image = 'https://jspm.org/jspm.png'
edit-url = 'https://github.com/jspm/jspm.org/blob/master'

[[task]]
name = 'generate:api-docs'
run = 'node ./scripts/api-docs-generator/generator.js'
